<?php
// Generated by ZF2's ./bin/classmap_generator.php
/**
 * Use command:
 * php path_to/classmap_generator.php -l ./src/ -o ./autoload_classmap.php -w
 *
 * @see http://framework.zend.com/manual/2.0/en/modules/zend.loader.classmap-generator.html
 */
return array(
  'yimaSkeletonModule\Controller\IndexController' => __DIR__ . '/src/yimaSkeletonModule/Controller/IndexController.php',
  'yimaSkeletonModule\Module'                     => __DIR__ . '/src/yimaSkeletonModule/Module.php',
);
